defaults: &defaults
  adapter: postgresql
  prepared_statements: false
  host: localhost
  encoding: unicode
  pool: 5
  username: Alex
  password:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

development:
  <<: *defaults
  database: psql_development

test:
  <<: *defaults
  database: psql_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *defaults
  database: psql_production
