# Dockerfile does COPY of this into
# config/database.yml so containers
# work correctly in docker compose

defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: Alex
  password:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

development: &default
  adapter: postgresql
  database: backbone_data_bootstrap_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: backbone_data_bootstrap_test

production:
  <<: *defaults
  database: psql_production
